### ISSUE TITLE
Cant find _slots.json file

### ISSUE THREAD

**Issue by zonneschijn7** [Shrimpsnail/Immersive-Interfaces#10]
Trying to enable slots for my language (netherlands), but cant find the _slots.json file. (description of mod says i need to rename that file to nl_nl_slots.json)

**Comment by Shrimpsnail** [comment]
I have forgotten to add the new language files to the 0.3 version as it was a branch specific addition that was a complete blunder on my part, i apologize.

you can rename the en_ut.json to nl_nl.json you shouldn't add slots to your language as it isn't set as a custom language in the pack.mcmeta, although if you with to set up a new custom language you can use the current mcmeta as a reference

**Comment by zonneschijn7** [comment]
Alright.
