### ISSUE TITLE
Durability bar in enderchest bugging out

### ISSUE THREAD

**Issue by zonneschijn7** [Shrimpsnail/Immersive-Interfaces#12]
Image:
![image](https://github.com/user-attachments/assets/5794de88-2355-4129-bd55-9de42af496ff)

All the netherite gear is damaged, the durability bar looks weird.

**Comment by Shrimpsnail** [comment]
Not fixable, i'll be having a mod language soon where it can let mods do the work instead of fonts but for vanilla there isn't much i can do
