### ISSUE TITLE
chests & villagers

### ISSUE THREAD

**Issue by operator-wind** [Shrimpsnail/Immersive-Interfaces#14]
my chests dont show items that are inside it so all i see is a picture of a chest + when i trade with villagers i dont see my emeralds or a product that i buy please i realy like the idea of this pack and i hope it will be a great pack when all the bugs/issues will be fixed

**Comment by operator-wind** [comment]
![image](https://github.com/user-attachments/assets/caa82459-d204-4cad-9d48-12e2af6b52cf)
there is a picture with a chest with an emerald in it

**Comment by Shrimpsnail** [comment]
Apologize for the lack of response this was at the start of burnout and got pushed to the bottom and i've lost track of support i've done, what version, mods and/or packs are you using?
