### ISSUE TITLE
[FEATURE] Adding different container sizes

### ISSUE THREAD

**Issue by illyrius666** [Shrimpsnail/Immersive-Interfaces#19]
As you can see in the picture below when having this RP on a server and using the plugin [CommandPanels](https://www.spigotmc.org/resources/commandpanels.67788/), there is not "chest" container texture for the custom sizes.
![image](https://github.com/user-attachments/assets/f9782d04-aa48-4128-85d0-5b755152e75e)

**Comment by illyrius666** [comment]
ow, is that a special way you assign those textures? because i have seen alot of texture packs who do feature this. isnt it by chance a default texture or something?

**Comment by illyrius666** [comment]
![generic_54](https://github.com/user-attachments/assets/9774a4d3-3d78-414e-9389-f7539e36aeed)
Here i found one from another texture pack where this works perfectly fine with that CommandPanels container

**Comment by Shrimpsnail** [comment]
My default texture isn't so much as a default, but instead a "Catch all" (this is why it's so small), A Functional UI in case the font UI fails for any reason.

I can change the ui itself to be red like the inventory that's just design at that point, as the UI works it's just not like the chests and such.

i think i can make that default ui better however, it's not something i've put much focus on

**Comment by illyrius666** [comment]
Yes obv take your time, i just found it a bit off place compared to the rest of your style.
