### ISSUE TITLE
horse inv

### ISSUE THREAD

**Issue by illyrius666** [Shrimpsnail/Immersive-Interfaces#20]
i looked at the roadmap and i noticed that horse armor is not done but neither planned.
![39e90a55d84f1648f2f0c35873a146d40f47b8c6](https://github.com/user-attachments/assets/c3e7e22d-e2cd-49fb-8313-35b8ff44d922)

**Comment by Shrimpsnail** [comment]
I just forgot it, it's both in my work area file thing, and I've added it to the Roadmap in it, it's a bit of a complex one with all the optiGUI possibilities so it's for when I experiment with them

![{E2FDC171-BA36-4C3F-9F24-615BB58D0123}](https://github.com/user-attachments/assets/f138d9aa-c070-4106-a18a-a490cea5d811)
