### ISSUE TITLE
Beta v0.4 not showing up in Resource Pack Menu

### ISSUE THREAD

**Issue by berwulf** [Shrimpsnail/Immersive-Interfaces#21]
I've tried cloning the mcmeta of the previous versions of the pack into the new update and just changing a few things and it still wouldnt appear, ive also tried deleting all the old ones still doesnt

**Comment by Shrimpsnail** [comment]
what does the folder look like, and the files? version you're using?

that's odd. the pack is zipped correctly when downloaded from other sources

**Comment by berwulf** [comment]
![image](https://github.com/user-attachments/assets/f2c6a597-3a44-4f8c-a7fb-e9e2d2f4d931)
Here ya go, it's on 1.21.1

I'm not sure either, but I did have recursive resources mod installed, it still wouldn't show up after i removed the mod. When i add other resource packs they appear, immersive interfaces is the one exception ._.

**Comment by Shrimpsnail** [comment]
Hmmm can you try renaming the file to remove the color codes? perhaps it has some issues with something there?

and can you try unzipping the resource pack?

**Comment by berwulf** [comment]
okiedokie hang on let me do that

**Comment by berwulf** [comment]
stiiilll not working for some reason :( 
[Immersive Interfaces 4.zip](https://github.com/user-attachments/files/17319180/Immersive.Interfaces.4.zip)

**Comment by Shrimpsnail** [comment]
I have found the issue, Recursive resources seems to have issues with loading packs with overlays, I'm unsure why removing it didn't fix the issue it might failsafe perhaps.

you can just remove the overlays and end with something like this, if you're on 1.20 that's all you have to do

```
{
	"pack": {
		"pack_format":34,
		"supported_formats": [15,34],
		"description": "Completely overhauled UI Beta V0.4 | By Shrimpsnail"
	},
	"language":{
		"en_us-slot":{
		"name":"English [Chest Slots]",
		"region":"US"
		}
	}
}
```

however if you're using a newer version like 1.21 you'll have to remove the assets folder and move the /main/assets to replace it as main was the overlay for the newer versions

**Comment by berwulf** [comment]
That did the trick! thank you :D 
![2024-10-11_06 20 29](https://github.com/user-attachments/assets/e92f16dd-2b04-4a1d-8ed7-73007e0149ff)

Keep up  the great work, the pack is amazing

**Comment by Shrimpsnail** [comment]
Great to know!, there seems to be a report on recursive resources github about the issue already, although i only found after i asked in the discord, so it might get fixed on their end.
