### ISSUE TITLE
Villager Ui issue

### ISSUE THREAD

**Issue by GTX1080TiBOOM** [Shrimpsnail/Immersive-Interfaces#23]
Villagers UI incorrectly displays double layers.
![QQ20241008-205315](https://github.com/user-attachments/assets/7cc9a331-01f0-4486-8d5c-abc976a125a2)

**Comment by GTX1080TiBOOM** [comment]
I tried to find the mod that caused this problem😵

**Comment by Shrimpsnail** [comment]
interesting it has a name but it's still showing the actual ui?

**Comment by GTX1080TiBOOM** [comment]
> 有趣的是，它有一个名称，但它仍然显示实际的 UI？
> 
> 通常命名村民会完全取代它

You are right! I know what the problem is! It's caused by "Villager Names"!
https://modrinth.com/mod/villager-names-serilum
