### ISSUE TITLE
conflict with Jade

### ISSUE THREAD

**Issue by trAshbaG1145** [Shrimpsnail/Immersive-Interfaces#25]
![77fac0d0-1638-4602-9adb-172da21bab59](https://github.com/user-attachments/assets/fc6cea79-3738-4b98-b286-964ebb6712b6)
as shown above

**Comment by trAshbaG1145** [comment]
chest, large chest, minecart with hopper and minecart with chest would make this bug to occur

**Comment by Shrimpsnail** [comment]
I'm aware of this issue, it's not fixable in vanilla but I'm currently fixing it by using the polytone features it will be in the next update
