### ISSUE TITLE
Hot bar not showing up and button in inventory not supposed to be there

### ISSUE THREAD

**Issue by tyler3184** [Shrimpsnail/Immersive-Interfaces#26]
I'm playing on 1.20.4 and the hot bar is just the vanilla hot bar and the button in my inventory is also a vanilla button. I have tried previous versions an nothing worked.
![IMG_7148](https://github.com/user-attachments/assets/022f849f-ad7d-4b17-8dc1-197b8ee46843)
![IMG_7149](https://github.com/user-attachments/assets/a0057009-a3bf-4d54-bbc1-d05b6a54dfdf)

**Comment by Shrimpsnail** [comment]
i believe it has something to do with the overlay being set to the wrong versions, i'll investigate

**Comment by tyler3184** [comment]
ok thanks

**Comment by tyler3184** [comment]
any updates?

**Comment by Shrimpsnail** [comment]
working on all of the other mod incompatibility issues it has currently!. i will still fix it before releasing the next update, i'll mention this here when i push a fix for this

**Comment by Shrimpsnail** [comment]
I've gotten no issues with the uis, hotbars and such, are you using any mods? it might be something related to the new polytone format still not working?

![2024-10-23_22 45 50](https://github.com/user-attachments/assets/458fea4c-c903-461d-a250-6a2369e20723)

**Comment by Shrimpsnail** [comment]
That was from downloading the zip directly from github this is the file although correctly zipped

[Immersive-Interfaces-main.zip](https://github.com/user-attachments/files/17498725/Immersive-Interfaces-main.zip)
