### ISSUE TITLE
villager pop-up covering my hotbar

### ISSUE THREAD

**Issue by maggie2800** [Shrimpsnail/Immersive-Interfaces#28]
help! i have this issue, half of the villager interface shows up in front of and covers my hotbar when i look at a villager and not even in their interface

**Comment by maggie2800** [comment]
![2024-10-14_00 29 13](https://github.com/user-attachments/assets/3e50766c-3641-4f2d-a9bd-6b89cd781daa)

**Comment by maggie2800** [comment]
well is there a way to get rid of the villager interface in the meantime, i tried deleting stuff from the resource pack folder but nothing worked

**Comment by Shrimpsnail** [comment]
Go into the lang file you use and remove any mentions of merchant professions and texts

**Comment by Shrimpsnail** [comment]
whoops

**Comment by maggie2800** [comment]
well deleted what you said and still whenever i just walk near a villager that interface pops up

**Comment by maggie2800** [comment]
![Screenshot 2024-10-20 162112](https://github.com/user-attachments/assets/00af9753-8982-44e2-9f37-b9aeb0d1c8a3)

**Comment by Shrimpsnail** [comment]
you also have to delete it from en_us my bad! i only found out recently that custom languages empty values take on the modified en_us from the resource pack not the vanilla, the new -slots json is already way smaller due to it

**Comment by maggie2800** [comment]
well shoot, in that time i downloaded presence footsteps and sound physics remastered and i guess it changed my whole lang file to look like this, lol maybe ill just wait for this to be fixes, but if you could help me out with this it would be great, i like the interfaces
![Screenshot 2024-11-02 120331](https://github.com/user-attachments/assets/8a7e0783-8d7b-4d62-b799-32110f0c0bb9)
