### ISSUE TITLE
Villager interface decentered in snapshots

### ISSUE THREAD

**Issue by Fleeepo** [Shrimpsnail/Immersive-Interfaces#29]
Any version that is not exactly 1.21.1 (I only tested new snapshots) breaks villager interfaces. 
Everything else works perfectly.
![Immagine 2024-10-20 161537](https://github.com/user-attachments/assets/b83216cb-cc19-4f7f-a7be-4be7f2e092e4)

**Comment by Shrimpsnail** [comment]
It seems that the snapshot versions that aren't the exact ones i tested have issues, i will be looking into this when i'm able to again after the rest of the update is done

**Comment by Fleeepo** [comment]
New discovery: on 1.21.2 normal villagers still don't work properly, but wandering traders do (kind of)
![2024-10-22_19 48 31](https://github.com/user-attachments/assets/a6a981a7-dcf3-46b9-a338-3586fa190c8d)
![2024-10-22_19 46 55](https://github.com/user-attachments/assets/ca608b3a-222e-4d61-ad04-2ece63ec8781)
