### ISSUE TITLE
[Question] Langfile generation script

### ISSUE THREAD

**Issue by Wolphwood** [Shrimpsnail/Immersive-Interfaces#3]
Hey 👋

I remade a more powerfull script for generating all langs files

How work my new script :
- Import "model" language file
- Gets a list in Map form of all files in __".minecraft/assets/objects/"__ `hash → full_path_to_file`
- Reads the most recent index in ".minecraft/assets/indexes/" and maps its contents. `filename.ext → { hash: "...", size: 0 }`
- Process the language list
 - key: "text"` : copy pastes text into output file.
 - `key: { text: "..." }` copy pastes text into output file.
 - `key: { prefix: "..." }` Adds a prefix to the original text and pastes it into the output file.
 - `key: { suffix: "..." }` Adds a suffix to the original text, then pastes it into the output file.
 **Note that 'text', 'prefix' and 'suffix' are not cumulative**.
- Export generated language file to __"<PathToRessourcePack>/assets/minecraft/lang/<lang>.json"__

it's a bit more complicated, but allows you to support color changes for certain translations in case copy/paste is not enough (like `gui.recipebook.search_hint`).

You can find it in my testing branch [[here]](https://github.com/Wolphwood/Immersive-Interfaces/blob/testing/readme/scripts/lang.js)

It's not fully documented yet and doesn't handle every errors, but this "beta" work fine!

BUT, not eveyone have node installed, so maybe i should compile it as .exe and give both .js and .exe files ?
→ .js file for who doesn't trust compiled version
→ .exe file ready to use for most of people.

![image](https://github.com/user-attachments/assets/e7d63523-3a32-443a-a315-9d65b9e87b96)
![image](https://github.com/user-attachments/assets/6d62f8c1-48e0-4a07-80a5-cebf8b2e7170)
![image](https://github.com/user-attachments/assets/c6507e9e-38c8-45c2-86c6-a4d1aacf72ca)
![image](https://github.com/user-attachments/assets/91a8adec-8e76-443e-82fe-dfa751606b97)
_don't worry about "?" chars, it's work like that, but i work to force the escaped format_

**Comment by Wolphwood** [comment]
Update : I fix the non escaped unicode chars 👍 
![image](https://github.com/user-attachments/assets/65e63de9-07ab-4eef-ae20-c42b38a3fee5)

**Comment by Shrimpsnail** [comment]
Ah i see the previous one had color issues? which is every ui line essentially, I'll test it later, and if the .js and .exe are present i don't see much of an issue for the github version aslong as it doesn't impact the size, needs more thought put into it than i can offer right now while working on the other aspects

**Comment by Wolphwood** [comment]
> Ah i see the previous one had color issues?

Yes, like `gui.recipebook.search_hint` became "§9Search..." in your pack, with the first script, it will copy "§9Search..." in every langages.

With the new, you can set as `gui.recipebook.search_hint: { prefix: "§9" }` and every lang will have the good translation but with the color "§9" !

**Comment by Shrimpsnail** [comment]
that should prove useful although for now since the vanilla shader isn't present the line is there from the other pack, it'll be organized when i clean all the recipe book designs into something more consistent
