### ISSUE TITLE
trade ui shows up with normal ui

### ISSUE THREAD

**Issue by HeroicPanda2137** [Shrimpsnail/Immersive-Interfaces#32]
![obraz_2024-10-28_011154007](https://github.com/user-attachments/assets/87e37325-983e-474f-9c57-8527901b02ae)
i dont know why it is occuring. mind helping please?

**Comment by Shrimpsnail** [comment]
This issue should be fixed in the dev version of github, you can try downloading from github directly, it's not zipped correctly and will need to be extracted.

it will be updated when i get the time

**Comment by HeroicPanda2137** [comment]
it worked when i downloaded it from github. thanks a lot :D

**Comment by Shrimpsnail** [comment]
great! , this will be in the next update as soon as i smooth everything else out
