### ISSUE TITLE
villager ui is buggy?

### ISSUE THREAD

**Issue by VaporeonScripts** [Shrimpsnail/Immersive-Interfaces#34]
![image](https://github.com/user-attachments/assets/f63625d4-8298-4690-9faf-69cfcf67cad1)

**Comment by Shrimpsnail** [comment]
The villager has a name, i forgot which mod added names, but the vanilla method doesn't support that, normally named villagers lose their respective uis.

There's also another resource pack which somehow manages to replace the trades text while not breaking my trades text
