### ISSUE TITLE
broken texture

### ISSUE THREAD

**Issue by VaporeonScripts** [Shrimpsnail/Immersive-Interfaces#36]
![image](https://github.com/user-attachments/assets/8312c1a1-a982-45d6-b6fc-df1c933c4ac0)

**Comment by VaporeonScripts** [comment]
(this res pack got higher priority than barely default, this happens tho)

**Comment by VaporeonScripts** [comment]
when the release?

**Comment by Shrimpsnail** [comment]
I am extremely busy for the next days, and i've been extremely sick the past days, it will take a while

**Comment by VaporeonScripts** [comment]
oh, alright

**Comment by VaporeonScripts** [comment]
the issue got fixed with polytone updates

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/26f4c348-b205-491d-b8b4-17fdf1c6d5da)

**Comment by VaporeonScripts** [comment]
the issue is still there :skull:

**Comment by Shrimpsnail** [comment]
it changed? ;-; i'll have to check it when i'm able to, this is the github or release?

**Comment by VaporeonScripts** [comment]
Release

**Comment by VaporeonScripts** [comment]
From.github,latest polytone
