### ISSUE TITLE
incompat with TES

### ISSUE THREAD

**Issue by VaporeonScripts** [Shrimpsnail/Immersive-Interfaces#38]
![image](https://github.com/user-attachments/assets/5aa6bd5f-5142-44f5-bf07-dfc89300edbb)

**Comment by VaporeonScripts** [comment]
https://www.curseforge.com/minecraft/mc-mods/tslatentitystatus-tes

**Comment by VaporeonScripts** [comment]
i got polytone, is there a way i can fix it? or what language do i choose?

**Comment by Shrimpsnail** [comment]
If you're using polytone you can change to modded language, however optigui is a to change the villager uis

**Comment by VaporeonScripts** [comment]
i dont have optigui tho, its not on neoforge

**Comment by Shrimpsnail** [comment]
Then you won't get the librarian texture, everything else should be fine. I can't do a librarian texture without issues currently

**Comment by VaporeonScripts** [comment]
aight
