### ISSUE TITLE
[Suggestion] Double resolution 

### ISSUE THREAD

**Issue by Arch23-tech** [Shrimpsnail/Immersive-Interfaces#4]
Hi there 👋.. Mr. Shrimp 

I fell in love with this sleek resource pack you made from the first sight (Lol).....

Anyways the resource pack is cool and it's quality and resolution is nice ....
But, I thought while some of us like to play with high resolution texture packs, I wish if you could develop a separate version of the exact resource pack but having doubled it's resolution 

This pack but with double resolution 

Thank youuuuu for this piece of art

**Comment by Shrimpsnail** [comment]
I appreciate the kind words, however double resolution is the one thing I am least likely to do with the pack, if anyone has any intentions of doing so they're free to ask for permission.

the GUI is already quite stylized and increase the resolution would quadruple the amount of pixels and the stylization I can get away with at this scale wouldn't work which could cause some issues with designs

**Comment by Shrimpsnail** [comment]
(learning github)
