### ISSUE TITLE
Backport for 1.20.1

### ISSUE THREAD

**Issue by ExpertFaun11492** [Shrimpsnail/Immersive-Interfaces#6]
There is a lot of mod-players (including me) playing at specific version 1.20.1 for the mods,and I really want to use this in my daily mod-craft life.
I think this is one of the best UI pack so if u can make it work on 1.20.1 we (at least me) will be very happy so please

ExpertFaun11492

**Comment by Shrimpsnail** [comment]
Repeat of #5 i'll repeat the comment as i was mostly unaware of how much people wanted it

added with the latest commit, it will be present in version 0.3,  if you end up testing it and find any issues please report.

Note any mods that showcase the name of a block or entity are most likely to show UIs in their name, in most cases i will be unlikely to change anything but having a list will still be useful
