### ISSUE TITLE
Villager UI appears with WTHIT mod installed

### ISSUE THREAD

**Issue by ChicagoSpud** [Shrimpsnail/Immersive-Interfaces#8]
when looking at a villager the ui shows up without opening it when the WTHIT mod is installed
![2024-09-15_05 33 54](https://github.com/user-attachments/assets/25583f2c-b9c1-4928-8005-ee6d3e3fdd6c)

**Comment by operator-wind** [comment]
same thing hapends to chests

**Comment by harpuppy** [comment]
also occurs with Jade mod. i believe it's related to the ui for the villagers & chests being embedded in the language file/text itself

**Comment by illyrius666** [comment]
yep i have this issue with Jade mod too.

**Comment by Shrimpsnail** [comment]
I have an idea to try and fix this with a modded specific language that uses polytone and optigui instead, so that there aren't so many issues with mods like Jade
