### ISSUE TITLE
Popular shopkeepers plugin not compitable with GUI

### ISSUE THREAD

**Issue by zonneschijn7** [Shrimpsnail/Immersive-Interfaces#9]
Please add it to be compatible with the shopkeepers plugin, the gui probably doesnt load because it is a 'jobless' villager.

**Comment by Shrimpsnail** [comment]
can you link what plugin this is?

**Comment by zonneschijn7** [comment]
It's https://www.spigotmc.org/threads/shopkeepers.447969/
